# cloudbuild.yaml
steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'clientBuildTesting']

  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--force']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app-testing.yaml']
